version: '3.8'

services:
  crypto_arena:
    build: .
    container_name: crypto_arena_50x
    restart: always
    ports:
      - "80:8088"
      - "8088:8088"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
